print("this is a test foruth file")
print("this is a test foruth file")
print("this is a test foruth file")
print("this is a test foruth file")
print("this is a test foruth file")
print("this is a test foruth file")

print("this is a test foruth file")
print("this is a test foruth file")
print("this is a test foruth file")
print("time flies")
